// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckQrcode(arg1) {
  return window['go']['main']['App']['CheckQrcode'](arg1);
}

export function DrawData(arg1) {
  return window['go']['main']['App']['DrawData'](arg1);
}

export function DrawData1(arg1) {
  return window['go']['main']['App']['DrawData1'](arg1);
}

export function GetAweme(arg1, arg2) {
  return window['go']['main']['App']['GetAweme'](arg1, arg2);
}

export function GetCode() {
  return window['go']['main']['App']['GetCode']();
}

export function GetFollow(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFollow'](arg1, arg2, arg3);
}

export function GetQueryUser(arg1) {
  return window['go']['main']['App']['GetQueryUser'](arg1);
}

export function GetRelation(arg1) {
  return window['go']['main']['App']['GetRelation'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogRedirect(arg1) {
  return window['go']['main']['App']['LogRedirect'](arg1);
}

export function SearchUser(arg1) {
  return window['go']['main']['App']['SearchUser'](arg1);
}
