// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {struct_data} from '../models';
import {sync} from '../models';

export function CheckQrcode(arg1:string):Promise<{[key: string]: string}>;

export function DrawData(arg1:string):Promise<struct_data.UserItem>;

export function DrawData1(arg1:string):Promise<sync.Map|boolean>;

export function GetAweme(arg1:string,arg2:string):Promise<{[key: string]: string}>;

export function GetCode():Promise<{[key: string]: string}>;

export function GetFollow(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: string}>;

export function GetQueryUser(arg1:string):Promise<{[key: string]: string}>;

export function GetRelation(arg1:string):Promise<{[key: string]: string}>;

export function Greet(arg1:string):Promise<string>;

export function LogRedirect(arg1:string):Promise<{[key: string]: string}>;

export function SearchUser(arg1:string):Promise<{[key: string]: string}>;
